In [1]:
# ============================================================
# DAY 6 - NUMPY PRACTICE NOTEBOOK
# Numerical Data Analysis using NumPy
# ============================================================

import numpy as np

print("=" * 70)
print("DAY 6 - NUMPY PRACTICE NOTEBOOK")
print("=" * 70)


# ============================================================
# 1. CREATING 1D, 2D AND 3D ARRAYS
# ============================================================

print("\n\n" + "=" * 70)
print("1. CREATING 1D, 2D AND 3D ARRAYS")
print("=" * 70)

# 1D Array
arr_1d = np.array([10, 20, 30, 40, 50])

# 2D Array
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# 3D Array
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print("\n1D Array:")
print(arr_1d)

print("\n2D Array:")
print(arr_2d)

print("\n3D Array:")
print(arr_3d)


# ============================================================
# 2. CHECKING DIMENSIONS AND DATA TYPES
# ============================================================

print("\n\n" + "=" * 70)
print("2. ARRAY DIMENSIONS AND DATA TYPES")
print("=" * 70)

print("\n1D Array Dimension:", arr_1d.ndim)
print("1D Array Shape:", arr_1d.shape)
print("1D Array Data Type:", arr_1d.dtype)

print("\n2D Array Dimension:", arr_2d.ndim)
print("2D Array Shape:", arr_2d.shape)
print("2D Array Data Type:", arr_2d.dtype)

print("\n3D Array Dimension:", arr_3d.ndim)
print("3D Array Shape:", arr_3d.shape)
print("3D Array Data Type:", arr_3d.dtype)


# ============================================================
# 3. INDEXING
# ============================================================

print("\n\n" + "=" * 70)
print("3. INDEXING")
print("=" * 70)

print("\n1D Array:", arr_1d)
print("First Element:", arr_1d[0])
print("Third Element:", arr_1d[2])
print("Last Element:", arr_1d[-1])

print("\n2D Array:")
print(arr_2d)
print("Element at Row 1, Column 2:", arr_2d[0, 1])
print("Element at Row 2, Column 3:", arr_2d[1, 2])

print("\n3D Array:")
print("Element at [0, 1, 2]:", arr_3d[0, 1, 2])


# ============================================================
# 4. SLICING
# ============================================================

print("\n\n" + "=" * 70)
print("4. SLICING")
print("=" * 70)

print("\nOriginal 1D Array:")
print(arr_1d)

print("First Three Elements:", arr_1d[:3])
print("Elements from Index 2:", arr_1d[2:])
print("Every Second Element:", arr_1d[::2])

print("\nOriginal 2D Array:")
print(arr_2d)

print("First Two Rows:")
print(arr_2d[:2])

print("First Two Columns:")
print(arr_2d[:, :2])

print("Rows 1-2 and Columns 2-3:")
print(arr_2d[:2, 1:])


# ============================================================
# 5. RESHAPING ARRAYS
# ============================================================

print("\n\n" + "=" * 70)
print("5. RESHAPING ARRAYS")
print("=" * 70)

original = np.arange(1, 13)

print("\nOriginal Array:")
print(original)

reshaped_2d = original.reshape(3, 4)

print("\nReshaped into 3 x 4:")
print(reshaped_2d)

reshaped_3d = original.reshape(2, 2, 3)

print("\nReshaped into 2 x 2 x 3:")
print(reshaped_3d)


# ============================================================
# 6. ARRAY GENERATION FUNCTIONS
# ============================================================

print("\n\n" + "=" * 70)
print("6. ARRAY GENERATION FUNCTIONS")
print("=" * 70)

# zeros()
zeros_array = np.zeros((3, 4))
print("\nzeros() - 3 x 4:")
print(zeros_array)

# ones()
ones_array = np.ones((2, 3))
print("\nones() - 2 x 3:")
print(ones_array)

# arange()
arange_array = np.arange(1, 11)
print("\narange() - Numbers from 1 to 10:")
print(arange_array)

# arange with step
arange_step = np.arange(0, 21, 5)
print("\narange() with step 5:")
print(arange_step)

# linspace()
linspace_array = np.linspace(0, 10, 6)
print("\nlinspace() - 6 equally spaced values:")
print(linspace_array)


# ============================================================
# 7. MATHEMATICAL OPERATIONS
# ============================================================

print("\n\n" + "=" * 70)
print("7. MATHEMATICAL OPERATIONS")
print("=" * 70)

a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print("\nArray A:", a)
print("Array B:", b)

print("\nAddition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDivision:")
print(a / b)

print("\nPower:")
print(a ** 2)

print("\nSquare Root of A:")
print(np.sqrt(a))


# ============================================================
# 8. VECTORIZED OPERATIONS
# ============================================================

print("\n\n" + "=" * 70)
print("8. VECTORIZED OPERATIONS")
print("=" * 70)

sales = np.array([100, 200, 300, 400, 500])

print("\nOriginal Sales:")
print(sales)

# Increase all sales by 10%
increased_sales = sales * 1.10

print("\nSales after 10% increase:")
print(increased_sales)

# Add fixed bonus
bonus_sales = sales + 50

print("\nSales after adding 50:")
print(bonus_sales)

# Calculate tax
tax = sales * 0.18

print("\n18% Tax:")
print(tax)

# Sales after tax
final_sales = sales + tax

print("\nSales including tax:")
print(final_sales)


# ============================================================
# 9. BOOLEAN MASKING
# ============================================================

print("\n\n" + "=" * 70)
print("9. BOOLEAN MASKING")
print("=" * 70)

numbers = np.array([10, 25, 40, 55, 70, 85, 100])

print("\nOriginal Array:")
print(numbers)

# Values greater than 50
mask = numbers > 50

print("\nBoolean Mask:")
print(mask)

print("\nValues greater than 50:")
print(numbers[mask])

# Values between 30 and 80
between = numbers[(numbers >= 30) & (numbers <= 80)]

print("\nValues between 30 and 80:")
print(between)


# ============================================================
# 10. BROADCASTING
# ============================================================

print("\n\n" + "=" * 70)
print("10. BROADCASTING")
print("=" * 70)

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

addition_value = 10

print("\nOriginal Matrix:")
print(matrix)

print("\nAdding 10 using Broadcasting:")
print(matrix + addition_value)

print("\nMultiplying by 2 using Broadcasting:")
print(matrix * 2)

# Broadcasting with a 1D array
row_values = np.array([1, 2, 3])

print("\nAdding [1, 2, 3] to each row:")
print(matrix + row_values)


# ============================================================
# 11. AGGREGATE FUNCTIONS
# ============================================================

print("\n\n" + "=" * 70)
print("11. AGGREGATE FUNCTIONS")
print("=" * 70)

data = np.array([10, 20, 30, 40, 50, 60, 70])

print("\nData:")
print(data)

print("\nSum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))

print("\nStandard Deviation:", np.std(data))
print("Variance:", np.var(data))


# ============================================================
# 12. AGGREGATE FUNCTIONS ON 2D ARRAY
# ============================================================

print("\n\n" + "=" * 70)
print("12. AGGREGATE FUNCTIONS ON 2D ARRAY")
print("=" * 70)

scores = np.array([
    [80, 85, 90],
    [70, 75, 80],
    [90, 95, 100]
])

print("\nScores:")
print(scores)

print("\nTotal:", np.sum(scores))
print("Average:", np.mean(scores))
print("Minimum:", np.min(scores))
print("Maximum:", np.max(scores))
print("Median:", np.median(scores))

print("\nColumn-wise Sum:")
print(np.sum(scores, axis=0))

print("\nRow-wise Sum:")
print(np.sum(scores, axis=1))

print("\nColumn-wise Mean:")
print(np.mean(scores, axis=0))

print("\nRow-wise Mean:")
print(np.mean(scores, axis=1))


# ============================================================
# 13. PRACTICAL NUMERICAL DATA ANALYSIS EXAMPLE
# ============================================================

print("\n\n" + "=" * 70)
print("13. PRACTICAL NUMERICAL DATA ANALYSIS")
print("=" * 70)

# Monthly sales data
monthly_sales = np.array([
    12000, 15000, 18000, 14000,
    20000, 22000, 19000, 25000,
    27000, 23000, 30000, 32000
])

print("\nMonthly Sales:")
print(monthly_sales)

print("\nTotal Annual Sales:", np.sum(monthly_sales))
print("Average Monthly Sales:", np.mean(monthly_sales))
print("Lowest Monthly Sales:", np.min(monthly_sales))
print("Highest Monthly Sales:", np.max(monthly_sales))
print("Median Monthly Sales:", np.median(monthly_sales))

# Months with sales above average
average_sales = np.mean(monthly_sales)

high_sales = monthly_sales[monthly_sales > average_sales]

print("\nAverage Sales:", average_sales)

print("\nMonths with Sales Above Average:")
print(high_sales)

# 10% growth projection
projected_sales = monthly_sales * 1.10

print("\nProjected Sales after 10% Growth:")
print(projected_sales)


# ============================================================
# 14. FINAL SUMMARY
# ============================================================

print("\n\n" + "=" * 70)
print("NUMPY PRACTICE COMPLETED SUCCESSFULLY")
print("=" * 70)

print("""
Topics Covered:
1. 1D, 2D and 3D Arrays
2. Array Dimensions
3. Shape and Data Types
4. Indexing
5. Slicing
6. Reshaping
7. zeros()
8. ones()
9. arange()
10. linspace()
11. Mathematical Operations
12. Vectorized Operations
13. Boolean Masking
14. Broadcasting
15. sum()
16. mean()
17. min()
18. max()
19. median()
20. Practical Numerical Data Analysis

NumPy Practice: COMPLETED
""")

print("=" * 70)

DAY 6 - NUMPY PRACTICE NOTEBOOK


1. CREATING 1D, 2D AND 3D ARRAYS

1D Array:
[10 20 30 40 50]

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


2. ARRAY DIMENSIONS AND DATA TYPES

1D Array Dimension: 1
1D Array Shape: (5,)
1D Array Data Type: int64

2D Array Dimension: 2
2D Array Shape: (3, 3)
2D Array Data Type: int64

3D Array Dimension: 3
3D Array Shape: (2, 2, 3)
3D Array Data Type: int64


3. INDEXING

1D Array: [10 20 30 40 50]
First Element: 10
Third Element: 30
Last Element: 50

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at Row 1, Column 2: 20
Element at Row 2, Column 3: 60

3D Array:
Element at [0, 1, 2]: 6


4. SLICING

Original 1D Array:
[10 20 30 40 50]
First Three Elements: [10 20 30]
Elements from Index 2: [30 40 50]
Every Second Element: [10 30 50]

Original 2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
First Two Rows:
[[10 20 30]
 [40 50 60]]
First Two Columns:
[[10 20]
 [40 50]
 [70 80]]
R